### PR TITLE
Added bower integration 

### PR DESCRIPTION
**Pull request by amoludage**
issue #7

### CODE REVIEW

**Comment by whackashoe** [comment]
Thanks a bunch man!

**Comment by whackashoe** [comment]
So when I do `bower install antimoderate` it resolves to `git://github.com/amoludage/antimoderate.git` - can you switch that to `git://github.com/whackashoe/antimoderate.git` ?

**Comment by amoludage** [comment]
yes of course :blush:

**Comment by amoludage** [comment]
:+1:  done, you can check `bower install antimoderate`  and it resolves to `git://github.com/whackashoe/antimoderate.git` 

Thanks :blush:

**Comment by whackashoe** [comment]
still doesn't here - does it cache for a while?

**Comment by amoludage** [comment]
yes, you need to clean cache using following command

`bower cache clean`

Thanks

**Comment by whackashoe** [comment]
aha great thanks man works now

**Pull request merged**
